wip
Signed-off-by: Jake Smith <jake.smith@lexisnexis.com>

diff --git a/initfiles/componentfiles/thor/start_slaves b/initfiles/componentfiles/thor/start_slaves
--- a/initfiles/componentfiles/thor/start_slaves
+++ b/initfiles/componentfiles/thor/start_slaves
@@ -16,19 +16,21 @@
 ################################################################################
 
 ip=$1
-master=$2
-masterport=$3
-logpth=$4
-instancedir=$5
-deploydir=$6
-hpcc_compname=$7
-hpcc_setenv=$8
-logredirect=$9
+slavenum=$2
+slaveport=$3
+master=$4
+masterport=$4
+logpth=$5
+instancedir=$6
+deploydir=$7
+hpcc_compname=$8
+hpcc_setenv=$9
+logredirect=$10
 
 source ${hpcc_setenv}
 
-if [ $# -lt 9 ]; then
-  echo usage: ip master masterport logdir workingdir deploydir hpcc_compname hpcc_setenv logredirect
+if [ $# -lt 11 ]; then
+  echo usage: ip slavenum slaveport master masterport logdir workingdir deploydir hpcc_compname hpcc_setenv logredirect
   exit 1
 fi
 
@@ -72,28 +74,15 @@ echo "slave(s) starting `date`"
 # create symlink for easier identification of slaves by compName
 ln -s -f $deploydir/thorslave_lcr thorslave_${hpcc_compname}
 
-# sync to current master thorgroup
-echo rsync -e "ssh -o StrictHostKeyChecking=no" $master:$instancedir/thorgroup $instancedir/thorgroup.slave
-rsync -e "ssh -o StrictHostKeyChecking=no" $master:$instancedir/thorgroup $instancedir/thorgroup.slave
+echo thorslave_$hpcc_compname master=$master:$masterport slave=.:$slaveport slavenum=$slavenum logDir=$logpth
+./thorslave_$hpcc_compname master=$master:$masterport slave=.:$slaveport slavenum=$slavenum logDir=$logpth 2>/dev/null 1>/dev/null &
+slavepid=$!
+PID_NAME="$PID/${hpcc_compname}_slave_${slavenum}.pid"
+echo $slavepid > $PID_NAME
+if [ "$slavepid" -eq "0" ]; then
+  echo "failed to start at `date`"
+  exit 1
+else
+  echo "slave pid $slavepid started `date`"
+fi
 
-let "slavenum = 1";
-for slave in $(cat $instancedir/thorgroup.slave); do
-  slaveip=${slave/:*/}
-  if [ ${slaveip} = ${ip} ]; then
-    slaveport=${slave/*:/}
-    if [ "$slaveport" = "" ]; then
-      slaveport=$THORSLAVEPORT
-    fi
-    echo thorslave_$hpcc_compname  master=$master:$masterport slave=.:$slaveport slavenum=$slavenum logDir=$logpth
-    ./thorslave_$hpcc_compname master=$master:$masterport slave=.:$slaveport slavenum=$slavenum logDir=$logpth 2>/dev/null 1>/dev/null &
-    slavepid=$!
-    PID_NAME="$PID/${hpcc_compname}_slave_${slavenum}.pid"
-    echo $slavepid > $PID_NAME
-    if [ "$slavepid" -eq "0" ]; then
-      echo "failed to start at `date`"
-    else
-      echo "slave pid $slavepid started `date`"
-    fi
-  fi
-  let "slavenum += 1";
-done
