wip

diff --git a/.github/workflows/build-containers-pr.yaml b/.github/workflows/build-containers-pr.yaml
--- a/.github/workflows/build-containers-pr.yaml
+++ b/.github/workflows/build-containers-pr.yaml
@@ -53,9 +53,7 @@ jobs:
 
       - name: tracing
         run: |
-          echo "Branch     = ${GITHUB_REF#refs/heads/}
-          echo "Base ref   = ${GITHUB_REF#refs/heads/}
-          echo "SHA        = ${{ steps.vars.outputs.sha}}"
+          echo "Base ref   = ${{ github.ref }}"
           echo "Action     = ${{ github.action }}"
           echo "Event      = ${{ github.event_name }}"
           echo "Actor      = ${{ github.actor }}"
@@ -97,17 +95,23 @@ jobs:
           build_prbase_missing=$(docker manifest inspect ${{ steps.vars.outputs.container_registry }}/${{ steps.vars.outputs.cr_user }}/${{ steps.vars.outputs.platform_build }}:${{ steps.vars.outputs.build_prbase_label }}-${{ github.event.pull_request.base.sha }} > /dev/null ; echo $?)
           echo build_base_missing=${build_base_missing}
           echo build_prbase_missing=${build_prbase_missing}
-          if [[ "${build_base_missing}" -eq "1" ]]
+          if [[ "${build_base_missing}" -eq 1 ]]
           then
             echo "Cannot find existing build base image, aborting"
             exit 1
           fi
-          if [[ "${build_prbase_missing}" -eq "1" ]]
-            echo "Current PR target branch image cannot be found, using latest"
-            echo ::set-output name=platform_prbase_ver=${{ steps.vars.outputs.build_prbase_label }}-latest
-          else
-            echo ::set-output name=platform_prbase_ver=${{ steps.vars.outputs.build_prbase_label }}-${{ github.event.pull_request.base.sha }}
+          if [[ "${build_prbase_missing}" -eq 1 ]]
           then
+            echo "Current PR target branch image cannot be found, using latest"
+            build_prbase_missing=$(docker manifest inspect ${{ steps.vars.outputs.container_registry }}/${{ steps.vars.outputs.cr_user }}/${{ steps.vars.outputs.platform_build }}:${{ steps.vars.outputs.build_prbase_label }}-latest > /dev/null ; echo $?)
+            if [[ "${build_prbase_missing}" -eq 1 ]]
+            then
+              echo "Cannot find the 'latest' target branch image, aborting"
+              exit 1
+            fi
+            echo ::set-output name=platform_prbase_ver::${{ steps.vars.outputs.build_prbase_label }}-latest
+          else
+            echo ::set-output name=platform_prbase_ver::${{ steps.vars.outputs.build_prbase_label }}-${{ github.event.pull_request.base.sha }}
           fi
          
       - name: PR image
